### ISSUE TITLE
[feature request] persisting data folder with rclone sync

### ISSUE THREAD

**Issue by pseudokawaii** [Suwayomi/Suwayomi-Server-docker#1]
It would be a great feature to implement since data cannot be persisted in PaaS with ephemeral file system. Like Heroku and Railway. You can see [this repo](https://github.com/cdr/deploy-code-server/tree/main/deploy-container#-persist-your-filesystem-with-rclone) for an example. As far as I understand, the Rclone setup doesn't need any modification on the application side, you only need to implement a sync/push button, or you could just make it so that the container automatically syncs the data folder with the cloud storage on a regular basis.

**Comment by arbuilder** [comment]
Data folder is already persistent if u have done volume mount as mentioned in readme. U can then do rsync/cloud backup on that directory.
Ex-
Persistent data of tachidesk on subsequent run
docker run -p 127.0.0.1:4567:4567 -v < folder path >:/./home/suwayomi/.local/share/Tachidesk ghcr.io/suwayomi/tachidesk

**Comment by pseudokawaii** [comment]
@arbuilder like I said earlier, I'm using a PaaS (https://railway.app) for deployment, and they only support Dockerfiles. How do you run that volume mounting command on a Dockerfile?

**Comment by arbuilder** [comment]
@pseudokawaii hmm, I don’t use use paas so I can’t comment on that. It looks to me your only option would be to add cloud sync support inside dockerfile. I won’t support that but I can help u in installing rsync inside dockerfile.

ping me on discord @ Mosei as it will be difficult to chat here

**Comment by pseudokawaii** [comment]
@arbuilder like [this one](https://github.com/cdr/deploy-code-server/blob/main/Dockerfile)?

**Comment by arbuilder** [comment]
https://discord.com/channels/801021177333940224/855025275258929162/887053094553260092

**Comment by arbuilder** [comment]
Make sure that u change the links of all the modified files used in dockerfile and startup scripts.

Closing this request, u can ping me on discord if there are issues
